spring.application.name=rion

spring.datasource.url=jdbc:mysql://ardkyertest1.mysql.database.azure.com/shop
spring.datasource.username=ardkyer
spring.datasource.password=REDACTED_DB_PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.cloud.aws.credentials.accessKey=${AWS_ACCESS_KEY_ID}
spring.cloud.aws.credentials.secretKey=${AWS_SECRET_ACCESS_KEY}
spring.cloud.aws.s3.bucket=ardkyerspring1
spring.cloud.aws.region.static=ap-northeast-2

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
logging.level.org.thymeleaf=TRACE
logging.level.org.springframework.web=DEBUG

spring.security.oauth2.client.registration.google.client-id=${client-id}
spring.security.oauth2.client.registration.google.client-secret=${client-secret}
spring.security.oauth2.client.registration.google.scope=email,profile

# Kakao OAuth2 Configuration
spring.security.oauth2.client.registration.kakao.client-id=${client-id-kakao}
spring.security.oauth2.client.registration.kakao.client-secret=${client-secret-kakao}
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.scope=profile_nickname
spring.security.oauth2.client.registration.kakao.client-name=Kakao
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post

# Kakao Provider Configuration
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id
